CREATE DATABASE IF NOT EXISTS dbstockly;

USE dbstockly;

CREATE TABLE IF NOT EXISTS Categorie (
  Id_Categorie INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Libelle_Categorie VARCHAR(25) NOT NULL,
  Description_Categorie VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS Produit (
  Id_Produit INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nom_Produit VARCHAR(100) NOT NULL,
  Prix_Produit INT NOT NULL,
  Quantite_Stock INT NOT NULL,
  Id_Categorie INT,
  FOREIGN KEY (Id_Categorie) REFERENCES Categorie(Id_Categorie)
);

CREATE TABLE IF NOT EXISTS Depense (
  Id_Depense INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Libelle_Depense VARCHAR(250) NOT NULL,
  Montant_Depense INT NOT NULL,
  Date_Depense DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Role (
  Id_Role INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Libelle_Role VARCHAR(25) NOT NULL,
  Mot_de_passe VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Utilisateur (
  Id_User INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nom_User VARCHAR(100) NOT NULL,
  Mot_de_passe VARCHAR(250) NOT NULL,
  Id_Role INT NOT NULL,
  FOREIGN KEY (Id_Role) REFERENCES Role(Id_Role)
);

CREATE TABLE IF NOT EXISTS Fournisseur (
  Id_Frs INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nom_Frs VARCHAR(250) NOT NULL,
  Contact_Frs VARCHAR(25),
  Adresse_Frs VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS Commande (
  Id_Commande INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Id_Produit INT,
  Id_Frs INT NOT NULL,
  Prix_Achat INT NOT NULL,
  Quantite_Cmd INT NOT NULL,
  Montant_Cmd INT NOT NULL,
  Date_Cmd DATETIME NOT NULL,
  FOREIGN KEY (Id_Produit) REFERENCES Produit(Id_Produit),
  FOREIGN KEY (Id_Frs) REFERENCES Fournisseur(Id_Frs)
);

CREATE TABLE IF NOT EXISTS Livraison (
  Id_Livraison INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Id_Commande INT NOT NULL,
  Date_Livraison DATETIME NOT NULL,
  FOREIGN KEY (Id_Commande) REFERENCES Commande(Id_Commande)
);

CREATE TABLE IF NOT EXISTS Vente (
  Id_Vente INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Id_Produit INT NOT NULL,
  Prix_Vente INT,
  Quantite_Vente INT,
  Montant_Vente INT,
  Date_Vente DATETIME NOT NULL,
  FOREIGN KEY (Id_Produit) REFERENCES Produit(Id_Produit)
);
